services:
  doc_pc:
    image: squidfunk/mkdocs-material
    restart: always
    network_mode: bridge
    tty: true
    volumes:
      - /root/Web/khm-doc-computer:/docs
    ports:
      - 8001:8000
  doc_dev:
    image: squidfunk/mkdocs-material
    restart: always
    network_mode: bridge
    tty: true
    volumes:
      - /root/Web/khm-note-dev:/docs
    ports:
      - 8002:8000
